#!/usr/bin/env node

/**
 * To deploy to a new slug run:
 *
 * $ node /path/to/this/file --namespace='ng-kube-test' --slug=foo --version=0.0.0
 */
const { execSync } = require('child_process');

getConsoleProject = () => {
  const cmd = 'gcloud config get-value project';
  try {
    return execSync(cmd, { encoding: 'utf-8' }).trim();
  } catch (error) {
    console.log('Could not return project name.', error);
    process.exit(1);
  }
};

const flags = process.argv.slice(2).reduce((json, input) => {
  const [, flag, value] = input.match(/^--([^=\s]*)=?(.*)/);
  json[flag.toLowerCase()] = value;
  return json;
}, {});

const env = {
  slug: flags.slug || 'baz',
  namespace: flags.namespace || 'ng-kube-test',
  imagePath: `gcr.io/${getConsoleProject()}/${flags.namespace || 'ng-kube-test'}:${flags.version || '0.0.0'}`,
  port: 4200,
};

const kubeResources = `
apiVersion: v1
kind: Namespace
metadata:
  name: ${env.namespace}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${env.slug}
  namespace: ${env.namespace}
  labels:
    run: ${env.slug}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ${env.slug}
  template:
    metadata:
      labels:
        run: ${env.slug}
    spec:
      containers:
      - name: ${env.slug}
        image: ${env.imagePath}
        ports:
        - containerPort: ${env.port}
        livenessProbe:
          httpGet:
            path: /${env.slug}/
            port: ${env.port}
          initialDelaySeconds: 90
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /${env.slug}/
            port: ${env.port}
          initialDelaySeconds: 90
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ${env.slug}
  labels:
    run: ${env.slug}
  namespace: ${env.namespace}
spec:
  ports:
  - port: ${env.port}
    targetPort: ${env.port}
  type: NodePort
  selector:
    run: ${env.slug}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${env.namespace}-ingress
  namespace: ${env.namespace}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ng-okay
          servicePort: 4200
        path: /ng-okay/*
      - backend:
          serviceName: ${env.slug}
          servicePort: 4200
        path: /${env.slug}/*`;

const deploySteps = [
  `docker build -t ${env.imagePath} --build-arg SLUG=${env.slug} .`,
  `docker push ${env.imagePath}`,
  `echo '${kubeResources}' > ./kubetemp.yaml`,
  `kubectl apply -f ./kubetemp.yaml -n=${env.namespace}`,
  `rm ./kubetemp.yaml`,
];

deploySteps.forEach(v => {
  execSync(v, {stdio: 'inherit'});
});

process.exit(1);
